__title__ = 'itj_process_controller'
__description__ = 'UI for controlling the Spatial Timber Assembly Process using Distributed Architectural Robots'
__url__ = 'https://github.com/gramaziokohler/itj_process_controller'
__version__ = '1.0.0'
__author__ = 'Victor Leung, Gramazio Kohler Research'
__author_email__ = 'leung@arch.ethz.ch'
__license__ = 'MIT license'
__copyright__ = 'Copyright 2018 Gramazio Kohler Research'